
2025-04-24 15:27:41 - DEBUG - utils.ssh_manager - SSH管理器初始化完成，使用设置: host=10.0.18.1, port=22, username=root
2025-04-24 15:27:41 - DEBUG - utils.ssh_manager - 尝试SSH连接 (第1次)
2025-04-24 15:27:51 - INFO - utils.ssh_manager - SSH连接成功
2025-04-24 15:27:51 - DEBUG - utils.test_case_executor - SSH连接验证成功
2025-04-24 15:27:51 - INFO - utils.test_case_executor - SSH连接就绪，初始化测试组件
2025-04-24 15:27:51 - DEBUG - utils.get_latest_image - 初始化 GetLatestImage 实例
2025-04-24 15:27:51 - DEBUG - utils.get_latest_image - 本地图像保存目录: E:\python\vp_180\data\img
2025-04-24 15:27:51 - DEBUG - utils.get_latest_screenshot - 初始化 GetLatestScreenshot 实例
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\Test_20250424152752.tiff
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 图像获取成功
2025-04-24 15:27:52 - DEBUG - utils.button_clicker - 找到按钮 电子放大 的坐标: (3749, 3999)
2025-04-24 15:27:52 - DEBUG - utils.button_clicker - 点击电子放大按钮 (3749, 3999)
2025-04-24 15:27:52 - DEBUG - utils.button_clicker - 执行命令: python3 /app/jzj/touch_click.py 3749 3999
2025-04-24 15:27:52 - DEBUG - utils.button_clicker - 点击按钮成功: ✅ 短按触摸事件已发送: X=3749, Y=3999
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\Test_20250424152752.tiff
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 15:27:52 - DEBUG - utils.get_latest_image - 图像获取成功
2025-04-24 15:29:57 - DEBUG - utils.ssh_manager - SSH管理器初始化完成，使用设置: host=10.0.18.1, port=22, username=root
2025-04-24 15:29:57 - DEBUG - utils.ssh_manager - 尝试SSH连接 (第1次)
2025-04-24 15:30:08 - INFO - utils.ssh_manager - SSH连接成功
2025-04-24 15:30:08 - DEBUG - utils.test_case_executor - SSH连接验证成功
2025-04-24 15:30:08 - INFO - utils.test_case_executor - SSH连接就绪，初始化测试组件
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 初始化 GetLatestImage 实例
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 本地图像保存目录: E:\python\vp_180\data\img
2025-04-24 15:30:08 - DEBUG - utils.get_latest_screenshot - 初始化 GetLatestScreenshot 实例
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\电子放大_20250424153008.tiff
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 15:30:08 - ERROR - utils.get_latest_image - 无法读取图像: E:\python\vp_180\data\img\电子放大_20250424153008.tiff
2025-04-24 15:30:08 - ERROR - utils.get_latest_image - 获取图像失败: 无法读取图像: E:\python\vp_180\data\img\电子放大_20250424153008.tiff
2025-04-24 15:30:08 - ERROR - utils.test_case_executor - 执行操作步骤时出错: 无法读取图像: E:\python\vp_180\data\img\电子放大_20250424153008.tiff
2025-04-24 15:30:08 - DEBUG - utils.button_clicker - 找到按钮 电子放大 的坐标: (3749, 3999)
2025-04-24 15:30:08 - DEBUG - utils.button_clicker - 点击电子放大按钮 (3749, 3999)
2025-04-24 15:30:08 - DEBUG - utils.button_clicker - 执行命令: python3 /app/jzj/touch_click.py 3749 3999
2025-04-24 15:30:08 - DEBUG - utils.button_clicker - 点击按钮成功: ✅ 短按触摸事件已发送: X=3749, Y=3999
2025-04-24 15:30:08 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 15:30:09 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 15:30:09 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 15:30:09 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 15:30:09 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 15:30:09 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\电子放大_20250424153008.tiff
2025-04-24 15:30:09 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 15:30:09 - ERROR - utils.get_latest_image - 无法读取图像: E:\python\vp_180\data\img\电子放大_20250424153008.tiff
2025-04-24 15:30:09 - ERROR - utils.get_latest_image - 获取图像失败: 无法读取图像: E:\python\vp_180\data\img\电子放大_20250424153008.tiff
2025-04-24 15:30:09 - ERROR - utils.test_case_executor - 执行操作步骤时出错: 无法读取图像: E:\python\vp_180\data\img\电子放大_20250424153008.tiff
2025-04-24 15:51:08 - DEBUG - utils.ssh_manager - SSH管理器初始化完成，使用设置: host=10.0.18.1, port=22, username=root
2025-04-24 15:51:08 - DEBUG - utils.ssh_manager - 尝试SSH连接 (第1次)
2025-04-24 15:51:19 - INFO - utils.ssh_manager - SSH连接成功
2025-04-24 15:51:19 - DEBUG - utils.test_case_executor - SSH连接验证成功
2025-04-24 15:51:19 - INFO - utils.test_case_executor - SSH连接就绪，初始化测试组件
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 初始化 GetLatestImage 实例
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 本地图像保存目录: E:\python\vp_180\data\img
2025-04-24 15:51:19 - DEBUG - utils.get_latest_screenshot - 初始化 GetLatestScreenshot 实例
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\电子放大_id_1_20250424155119.tiff
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 15:51:19 - ERROR - utils.get_latest_image - 无法读取图像: E:\python\vp_180\data\img\电子放大_id_1_20250424155119.tiff
2025-04-24 15:51:19 - ERROR - utils.get_latest_image - 获取图像失败: 无法读取图像: E:\python\vp_180\data\img\电子放大_id_1_20250424155119.tiff
2025-04-24 15:51:19 - ERROR - utils.test_case_executor - 执行操作步骤时出错: 无法读取图像: E:\python\vp_180\data\img\电子放大_id_1_20250424155119.tiff
2025-04-24 15:51:19 - DEBUG - utils.button_clicker - 找到按钮 电子放大 的坐标: (3749, 3999)
2025-04-24 15:51:19 - DEBUG - utils.button_clicker - 点击电子放大按钮 (3749, 3999)
2025-04-24 15:51:19 - DEBUG - utils.button_clicker - 执行命令: python3 /app/jzj/touch_click.py 3749 3999
2025-04-24 15:51:19 - DEBUG - utils.button_clicker - 点击按钮成功: ✅ 短按触摸事件已发送: X=3749, Y=3999
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 15:51:19 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 15:51:20 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 15:51:20 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\电子放大_id_3_20250424155119.tiff
2025-04-24 15:51:20 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 15:51:20 - ERROR - utils.get_latest_image - 无法读取图像: E:\python\vp_180\data\img\电子放大_id_3_20250424155119.tiff
2025-04-24 15:51:20 - ERROR - utils.get_latest_image - 获取图像失败: 无法读取图像: E:\python\vp_180\data\img\电子放大_id_3_20250424155119.tiff
2025-04-24 15:51:20 - ERROR - utils.test_case_executor - 执行操作步骤时出错: 无法读取图像: E:\python\vp_180\data\img\电子放大_id_3_20250424155119.tiff
2025-04-24 15:56:36 - DEBUG - utils.ssh_manager - SSH管理器初始化完成，使用设置: host=10.0.18.1, port=22, username=root
2025-04-24 15:56:36 - DEBUG - utils.ssh_manager - 尝试SSH连接 (第1次)
2025-04-24 15:56:46 - INFO - utils.ssh_manager - SSH连接成功
2025-04-24 15:56:46 - DEBUG - utils.test_case_executor - SSH连接验证成功
2025-04-24 15:56:46 - INFO - utils.test_case_executor - SSH连接就绪，初始化测试组件
2025-04-24 15:56:46 - DEBUG - utils.get_latest_image - 初始化 GetLatestImage 实例
2025-04-24 15:56:46 - DEBUG - utils.get_latest_image - 本地图像保存目录: E:\python\vp_180\data\img
2025-04-24 15:56:47 - DEBUG - utils.get_latest_screenshot - 初始化 GetLatestScreenshot 实例
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\电子放大_id_1_20250424155647.tiff
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 15:56:47 - ERROR - utils.get_latest_image - 无法读取图像: E:\python\vp_180\data\img\电子放大_id_1_20250424155647.tiff
2025-04-24 15:56:47 - ERROR - utils.get_latest_image - 获取图像失败: 无法读取图像: E:\python\vp_180\data\img\电子放大_id_1_20250424155647.tiff
2025-04-24 15:56:47 - ERROR - utils.test_case_executor - 执行操作步骤时出错: 无法读取图像: E:\python\vp_180\data\img\电子放大_id_1_20250424155647.tiff
2025-04-24 15:56:47 - DEBUG - utils.button_clicker - 找到按钮 电子放大 的坐标: (3749, 3999)
2025-04-24 15:56:47 - DEBUG - utils.button_clicker - 点击电子放大按钮 (3749, 3999)
2025-04-24 15:56:47 - DEBUG - utils.button_clicker - 执行命令: python3 /app/jzj/touch_click.py 3749 3999
2025-04-24 15:56:47 - DEBUG - utils.button_clicker - 点击按钮成功: ✅ 短按触摸事件已发送: X=3749, Y=3999
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\电子放大_id_1_20250424155647.tiff
2025-04-24 15:56:47 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 15:56:47 - ERROR - utils.get_latest_image - 无法读取图像: E:\python\vp_180\data\img\电子放大_id_1_20250424155647.tiff
2025-04-24 15:56:47 - ERROR - utils.get_latest_image - 获取图像失败: 无法读取图像: E:\python\vp_180\data\img\电子放大_id_1_20250424155647.tiff
2025-04-24 15:56:47 - ERROR - utils.test_case_executor - 执行操作步骤时出错: 无法读取图像: E:\python\vp_180\data\img\电子放大_id_1_20250424155647.tiff
2025-04-24 16:00:48 - DEBUG - utils.ssh_manager - SSH管理器初始化完成，使用设置: host=10.0.18.1, port=22, username=root
2025-04-24 16:00:48 - DEBUG - utils.ssh_manager - 尝试SSH连接 (第1次)
2025-04-24 16:00:58 - INFO - utils.ssh_manager - SSH连接成功
2025-04-24 16:00:58 - DEBUG - utils.test_case_executor - SSH连接验证成功
2025-04-24 16:00:58 - INFO - utils.test_case_executor - SSH连接就绪，初始化测试组件
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 初始化 GetLatestImage 实例
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 本地图像保存目录: E:\python\vp_180\data\img
2025-04-24 16:00:58 - DEBUG - utils.get_latest_screenshot - 初始化 GetLatestScreenshot 实例
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\id_1_20250424160058.tiff
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 16:00:58 - DEBUG - utils.get_latest_image - 图像获取成功
2025-04-24 16:00:58 - DEBUG - utils.button_clicker - 找到按钮 电子放大 的坐标: (3749, 3999)
2025-04-24 16:00:58 - DEBUG - utils.button_clicker - 点击电子放大按钮 (3749, 3999)
2025-04-24 16:00:58 - DEBUG - utils.button_clicker - 执行命令: python3 /app/jzj/touch_click.py 3749 3999
2025-04-24 16:00:59 - DEBUG - utils.button_clicker - 点击按钮成功: ✅ 短按触摸事件已发送: X=3749, Y=3999
2025-04-24 16:00:59 - DEBUG - utils.get_latest_image - 检查远程目录结构
2025-04-24 16:00:59 - DEBUG - utils.get_latest_image - 找到以下图像文件: ['/ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605989.tiff', '/ue/ue_harddisk/ue_data/2504151615/B/161605811.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600700.tiff', '/ue/ue_harddisk/ue_data/2504151615/A/161600475.tiff']
2025-04-24 16:00:59 - DEBUG - utils.get_latest_image - 找到最新图像文件: /ue/ue_harddisk/ue_data/2504151615/B/161606178.tiff
2025-04-24 16:00:59 - DEBUG - utils.get_latest_image - 开始下载图像文件
2025-04-24 16:00:59 - DEBUG - utils.get_latest_image - 解码并保存图像
2025-04-24 16:00:59 - DEBUG - utils.get_latest_image - 已保存图像到: E:\python\vp_180\data\img\id_1_20250424160059.tiff
2025-04-24 16:00:59 - DEBUG - utils.get_latest_image - 读取图像数据
2025-04-24 16:00:59 - DEBUG - utils.get_latest_image - 图像获取成功
